AMAZON_FREERTOS_3RD_PARTY_DIR := freertos/libraries/3rdparty
COMPONENT_SRCDIRS := $(AMAZON_FREERTOS_ABSTRACTIONS_DIR)/tracealyzer_recorder
COMPONENT_ADD_INCLUDEDIRS += $(AMAZON_FREERTOS_3RD_PARTY_DIR)/tracealyzer_recorder/include
COMPONENT_ADD_INCLUDEDIRS += $(AMAZON_FREERTOS_3RD_PARTY_DIR)/tracealyzer_recorder/config
COMPONENT_PRIV_INCLUDEDIRS += $(AMAZON_FREERTOS_3RD_PARTY_DIR)/tracealyzer_recorder/include
COMPONENT_PRIV_INCLUDEDIRS += $(AMAZON_FREERTOS_3RD_PARTY_DIR)/tracealyzer_recorder/config